name: 自动化部署

on:
  push:
    branches:
      - main  # 当 main 分支有 push 行为时触发
    paths_ignore:
      - .github/workflows/cicd.yml, # 忽略 .github/workflows/cicd.yml 文件
      - .github/workflows/ci.yml # 忽略 .github/workflows/ci.yml 文件

jobs:
  deloy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


        # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with: 
          node-version: '18.x.x'
        run: |
          npm install
          npm run build


        # 部署到github
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main # 指定部署的分支
          public_dir: ./dist # 指定部署的目录
          github_token: ${{ secrets.CICDDEMO }} # 使用 GitHub Token 
          commit_message: 'Deploy from workflow' # 提交信息